networks:
  single-service-network:
    driver: bridge

services:
  single:
    build:
      context: .
      dockerfile: Dockerfile
      target: single_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - single-service-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
